# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13bbca5129a0b7bd4d83f76c386950781aa5a6cd76084a98d3a8015f2096261925609d2689024d72cc0c3c5e77fbefab44280439b3e5b241cd7b0756cfa73457

test:
  secret_key_base: ef23e1d609fb77a56cb3af26d4464ccb1b21adb36357b079ead68164341d6b3749239769a1358320e914658207d486a580ce9ed2ed8194cc4983709e27f20d4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
